project_id = "jdmgwvewvaluchnvlkzd"

[functions.send-notification]
verify_jwt = false

[functions.predict-video]
verify_jwt = false

[functions.auto-answer]
verify_jwt = false

[functions.fused-score]
verify_jwt = false
